export const ADD_TO_CART = 'MINIMAL_STORE/CART/ADD_TO_CART';
export const CHANGE_ATTRIBUTES= 'MINIMAL_STORE/CART/CHANGE_ATTRIBUTES';
export const INCREMENT_AN_ITEM = 'MINIMAL_STORE/CART/INCREMENT_AN_ITEM';
export const DECREMENT_AN_ITEM = 'MINIMAL_STORE/CART/DECREMENT_AN_ITEM';
export const REMOVE_FROM_CART = 'MINIMAL_STORE/CART/REMOVE_FROM_CART';