export const GET_PRODUCTS = 'GET_PRODUCTS';
export const SELECT_ATTRIBUTE = 'SELECT_ATTRIBUTE';
export const UPDATE_ACTIVE_PRODUCT = 'UPDATE_ACTIVE_PRODUCT';
export const RESET_PRODUCT_ATTRIBUTES = 'RESET_PRODUCT_ATTRIBUTES';
